In [1]:
import numpy as np

In [2]:
def readFile(fn):
    todo  = np.loadtxt(fn, delimiter=',')
    datos = todo[:,:-1].copy() # Coge sólo las columnas de datos
    resul = todo[:,-1].copy()  # Coge sólo la columna de resultado (etiqueta)
    return datos, resul

In [3]:
datos, resul = readFile("../../../datos/botnet_tot_syn_l.csv")

In [6]:
f, c = np.shape(datos)
print(f, "||", c)

1000000 || 11


In [8]:
media = np.zeros([1, c])
std   = np.zeros([1, c])

media, std

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [9]:
media = np.sum(datos, axis=0)/f
std   = np.sqrt(np.sum(np.power(np.subtract(datos, media[None]), 2), axis = 0)/float(f))

media, std

(array([1.28153827e+03, 2.12827672e+04, 6.94805718e+03, 6.26311961e+04,
        1.22198595e+08, 1.57222361e+07, 9.10731393e+00, 1.88975480e+00,
        1.24270159e+02, 2.13060301e+09, 2.26149180e+09]),
 array([1.60589322e+03, 2.41174750e+04, 1.63949454e+04, 1.34264218e+05,
        2.33920714e+08, 4.41237795e+07, 5.28172581e+00, 2.10134561e+00,
        9.03431222e+01, 7.13843443e+08, 1.30153195e+09]))

In [11]:
datos_normalizados = (datos - media)/std
datos_normalizados

array([[-7.92409775e-01, -8.13093708e-01, -4.22450764e-01, ...,
         8.27177994e-01,  4.73166157e-01,  1.58951724e-01],
       [ 1.44372040e+00,  1.11636100e+00,  3.91275636e-01, ...,
         1.02641833e+00, -8.28695452e-01,  1.58948532e-01],
       [-7.98021657e-01, -8.82462456e-01, -4.20559921e-01, ...,
         1.02641833e+00,  4.73166118e-01,  1.85749013e-01],
       ...,
       [-7.98021657e-01,  5.94307946e-01, -4.18913078e-01, ...,
         8.71453555e-01,  2.20786283e+00,  1.58948532e-01],
       [-7.98021657e-01,  8.91950823e-04, -4.20559921e-01, ...,
         9.48936012e-01, -8.91330613e-01,  1.58949486e-01],
       [ 1.44368325e+00, -8.82462465e-01, -4.22267780e-01, ...,
        -7.11400672e-01,  4.73166157e-01, -8.96911346e-01]])